module.exports = {
  "autoComplete/0.1.1/index":"modules/autoComplete/0.1.1/index.js",
  "autoComplete/0.1.2/index":"modules/autoComplete/0.1.2/index.js",
  "monitor/0.1.0/index": "modules/monitor/0.1.0/index.js",
  "monitor/0.3.0/index": "modules/monitor/0.3.0/index.js",
  "calchart/0.1.0/index": "modules/calchart/0.1.0/index.js",
  "scrollspy/0.1.0/index": "modules/scrollspy/0.1.0/index.js",
  "customtrip/0.1.0/index": "modules/customtrip/0.1.0/index.js",
  "linefeature/0.1.0/index": "modules/linefeature/0.1.0/index.js",
  "topSlider/0.1.0/index": "modules/topSlider/0.1.0/index.js",
  "visa/0.1.0/index": "modules/visa/0.1.0/index.js",
  "mSlider/0.1.0/index": "modules/mSlider/0.1.0/index.js",
  "hotTuijian/0.1.0/index": "modules/hotTuijian/0.1.0/index.js",
  "abTrip/0.1.0/index": "modules/abTrip/0.1.0/index.js",
  "calendar/0.1.0/index": "modules/calendar/0.1.0/index.js",
  "calendar/0.1.0/comcal": "modules/calendar/0.1.0/comcal.js",
  "tab/0.1.0/index": "modules/tab/0.1.0/index.js",
  "serialize/0.1.0/index": "modules/serialize/0.1.0/index.js",
  "slider/0.1.0/index": "modules/slider/0.1.0/index.js",
  "lazyload/0.2.0/index": "modules/lazyload/0.2.0/index.js",
  "placeholder/2.0.8/placeholder": "modules/placeholder/2.0.8/placeholder.js",
  "acharts/0.1.0/index": "modules/acharts/0.1.0/index.js",
  "common/0.1.0/index": "modules/common/0.1.0/index.js",
  "sComments/0.1.0/index": "modules/sComments/0.1.0/index.js",
  "calendar/0.1.0/discount": "modules/calendar/0.1.0/discount.js",
  "calendar/0.1.1/comcal": "modules/calendar/0.1.1/comcal.js",
  "comment/0.2.1/index": "modules/comment/0.2.1/index.js",
  "comment/0.1.0/index": "modules/comment/0.1.0/index.js",
  "comment/0.2.0/comment.css": "modules/comment/0.2.0/comment.css",
  "comment/0.2.1/comment.css": "modules/comment/0.2.1/comment.css",
  "route/0.1.0/index": "modules/route/0.1.0/index.js",
  "dialog/0.1.0/index": "modules/dialog/0.1.0/index.js",
  "dialog/0.2.0/dialog": "modules/dialog/0.2.0/dialog.js",
  "dialog/0.1.0/config": "modules/dialog/0.1.0/config.js",
  "dialog/0.1.0/index.css": "modules/dialog/0.1.0/index.css",
  "calendar/0.1.0/index.css": "modules/calendar/0.1.0/index.css",
  "calendar/0.1.1/index": "modules/calendar/0.1.1/index.js",
  "calendar/0.1.1/index.css": "modules/calendar/0.1.1/index.css",
  "calendar/0.2.0/index": "modules/calendar/0.2.0/index.js",
  "share/0.1.0/index": "modules/share/0.1.0/index.js",
  "login/0.1.0/index": "modules/login/0.1.0/index.js",
  "pager/0.1.0/index": "modules/pager/0.1.0/index.js",
  "pager/0.2.1/index": "modules/pager/0.2.1/index.js",
  "pager/0.4.0/index": "modules/pager/0.4.0/index.js",
  "freePackage/pager/0.2.1/index": "modules/freePackage/pager/0.2.1/index.js",
  "packaged/0.1.0/index": "modules/packaged/0.1.0/index.js",
  "packaged/0.1.0/index.css": "modules/packaged/0.1.0/index.css",
  "transport/0.1.0/index": "modules/transport/0.1.0/index.js",
  "visa/0.2.0/index": "modules/visa/0.2.0/index.js",
  "jCarousel/0.1.1/index": "modules/jCarousel/0.1.1/index.js",
  "freePackage/packaged/0.1.0/index": "modules/freePackage/packaged/0.1.0/index.js",
  "googleMap/0.1.0/index": "modules/googleMap/0.1.0/index.js",
  "common/0.1.0/ua": "modules/common/0.1.0/ua.js",
  "common/0.1.0/json": "modules/common/0.1.0/json.js",
  "dialog/0.1.0/popup": "modules/dialog/0.1.0/popup.js",
  "datepicker/0.2.0/calendar-group": "modules/datepicker/0.2.0/calendar-group.js",
  "datepicker/0.2.0/datepicker": "modules/datepicker/0.2.0/datepicker.js",
  "datepicker/0.2.0/tmpl/calendar-group": "modules/datepicker/0.2.0/tmpl/calendar-group.js",
  "datepicker/0.2.0/tmpl/datepicker": "modules/datepicker/0.2.0/tmpl/datepicker.js",
  "panel/0.2.0/panel": "modules/panel/0.2.0/panel.js",
  "dialog/0.2.0/base": "modules/dialog/0.2.0/base.js",
  "intellSearch/0.2.1/track": "modules/intellSearch/0.2.1/track.js",
  "intellSearch/0.2.1/jsonDB": "modules/intellSearch/0.2.1/jsonDB.js",
  "intellSearch/0.2.1/searchBase": "modules/intellSearch/0.2.1/searchBase.js",
  "route/0.3.0/index": "modules/route/0.3.0/index.js",
  "jsextend/0.1.0/jsextend": "modules/jsextend/0.1.0/jsextend.js",
  "jsondb/0.1.0/dbstorage": "modules/jsondb/0.1.0/dbstorage.js",
  "comment/0.3.0/index": "modules/comment/0.3.0/index.js",
  "jsondb/0.1.0/jsondb": "modules/jsondb/0.1.0/jsondb.js",
  "freePackage/pager/0.2.2/index": "modules/freePackage/pager/0.2.2/index.js",
  "freePackage/pager/0.2.2/index.css": "modules/freePackage/pager/0.2.2/index.css",
  "datepicker/0.2.0/theme/calendar-group.css": "modules/datepicker/0.2.0/theme/calendar-group.css",
  "datepicker/0.2.0/theme/default.css": "modules/datepicker/0.2.0/theme/default.css",
  "validate/1.0.0/validate": "modules/validate/1.0.0/validate.js",
  "validate/1.0.0/rules": "modules/validate/1.0.0/rules.js",
  "validate/1.0.0/validate.css": "modules/validate/1.0.0/validate.css",
  "popup/0.2.0/popup.css": "modules/popup/0.2.0/popup.css",
  "datepicker/0.2.1/datepicker": "modules/datepicker/0.2.1/datepicker.js",
  "fonticon/0.1.0/fonticon.css": "modules/fonticon/0.1.0/fonticon.css",
  "jquery": "modules/jquery.js",
  "sea": "modules/sea.js",
  "dot": "modules/dot.js",
  "base/0.1.0/base": "modules/base/0.1.0/base.js",
  "base/0.1.0/module": "modules/base/0.1.0/module.js",
  "base/0.2.0/base": "modules/base/0.2.0/base.js",
  "base/0.2.0/module": "modules/base/0.2.0/module.js",
  "sea-debug": "modules/sea-debug.js",
  "slidertoolbar/0.1.0/index":"modules/slidertoolbar/0.1.0/index.js",
  "slidertoolbar/0.1.0/index.css":"modules/slidertoolbar/0.1.0/index.css",
  "slidertoolbar/0.1.0/tmpl/main":"modules/slidertoolbar/0.1.0/tmpl/main.js",
  "freePackage/search/0.1.0/index":"modules/freePackage/search/0.1.0/index.js",
  "freePackage/search/0.1.0/index.css":"modules/freePackage/search/0.1.0/index.css",
  "popup/0.2.0/popup":"modules/popup/0.2.0/popup.js",
  "popup/0.3.0/popup":"modules/popup/0.3.0/popup.js",
  "common/0.1.0/storage": "modules/common/0.1.0/storage.js",
  "common/0.1.0/es5.js ": "modules/common/0.1.0/es5.js",
  "dialog/0.2.0/dialog.css": "modules/dialog/0.2.0/dialog.css",
  "jCarousel/0.2.0/index": "modules/jCarousel/0.2.0/index.js",
  "pager/0.3.0/index": "modules/pager/0.3.0/index.js",
  "datepicker/0.2.1/theme/default.css":"modules/datepicker/0.2.1/theme/default.css",
  "departure/0.1.0/index":"/modules/departure/0.1.0/index.js",
  "lazyload/0.1.0/index": "modules/lazyload/0.1.0/index.js",
  "comment/0.3.0/visacomment":"modules/comment/0.3.0/visacomment",
  "dialog/0.2.2/dialog":"modules/dialog/0.2.2/dialog.js",
  "dialog/0.4.0/dialog":"modules/dialog/0.4.0/dialog.js",
  "calendar/0.3.2/index": "modules/calendar/0.3.2/index.js",
  "calendar/0.3.0/index": "modules/calendar/0.3.0/index.js",
  "calendar/0.3.0/discount": "modules/calendar/0.3.0/discount.js",
  "calendar/0.3.0/comcal": "modules/calendar/0.3.0/comcal.js",
  "calendar/0.3.1/index": "modules/calendar/0.3.1/index.js",
  "calendar/0.3.1/comcal": "modules/calendar/0.3.1/comcal.js",
  "scrollspy/2.0.0/index": "modules/scrollspy/2.0.0/index.js",
  "priceinform/0.1.0/index": "modules/priceinform/0.1.0/index.js",
  "freeRoute/0.2.0/index": "modules/freeRoute/0.2.0/index.js",
  "datepicker/0.2.1/calendar-year":"modules/datepicker/0.2.1/calendar-year.js",
  "datepicker/0.2.1/calendar-month":"modules/datepicker/0.2.1/calendar-month.js",
  "intellSearch/0.2.1/index": "modules/intellSearch/0.2.1/index.js",
  "intellSearch/0.2.1/search": "modules/intellSearch/0.2.1/search.js",
  "intellSearch/0.2.1/search-label": "modules/intellSearch/0.2.1/search-label.js",
  "intellSearch/0.2.1/intellSearch": "modules/intellSearch/0.2.1/intellSearch.js",
  "intellSearch/0.2.1/history": "modules/intellSearch/0.2.1/history.js",
  "intellSearch/0.2.1/hotcity": "modules/intellSearch/0.2.1/hotcity.js",
  "departure/0.2.0/index": "modules/departure/0.2.0/index.js",
  "lazyload/0.2.1/index": "modules/lazyload/0.2.1/index.js",
  "jCarousel/0.2.1/index": "modules/jCarousel/0.2.1/index.js",
  "sites/stat/statui/index.js":"sites/stat/statui/index.js",
  "calendar/0.2.0/discount": "modules/calendar/0.2.0/discount.js",
  "slidertoolbar/0.1.0/tool": "modules/slidertoolbar/0.1.0/tool.js",
  "calendar/0.2.0/comcal": "modules/calendar/0.2.0/comcal.js",
  "qrcode/0.1.0/index": "modules/qrcode/0.1.0/index.js",
  "unslider/2.0.0/index":"modules/unslider/2.0.0/index.js",
  "imgupload/0.1.0/imgupload":"modules/imgupload/0.1.0/imgupload.js",
  "imgupload/0.1.0/dist/lrz.bundle":"modules/imgupload/0.1.0/dist/lrz.bundle.js",
  "datepicker/0.2.1/tmpl/calendar-group":"modules/datepicker/0.2.1/tmpl/calendar-group.js",
  "datepicker/0.2.1/tmpl/datepicker":"modules/datepicker/0.2.1/tmpl/datepicker.js",
  "datepicker/0.2.1/tmpl/monthpanel":"modules/datepicker/0.2.1/tmpl/monthpanel.js",
  "datepicker/0.2.1/tmpl/yearpanel":"modules/datepicker/0.2.1/tmpl/yearpanel.js",
  "datepicker/0.2.1/tmpl/calendar": "modules/datepicker/0.2.1/tmpl/calendar.js",
  "calendar/0.3.0/festivals": "modules/calendar/0.3.0/festivals.js",
  "drag/0.3.0/jquery.dragsort":"modules/drag/0.3.0/jquery.dragsort.js",
  "drag/0.3.0/drag": "modules/drag/0.3.0/drag.js",
  "base/0.4.0/react-module":"modules/base/0.4.0/react-module.js",
  "popup/0.3.2/popup":"modules/popup/0.3.2/popup.js",
  "formsearch/0.4.0/formsearch":"modules/formsearch/0.4.0/formsearch.js",
  "paging/0.4.0/paging":"modules/paging/0.4.0/paging.js",
  "uplodify/0.3.1/h5upload":"modules/uplodify/0.3.1/h5upload.js",
  "picpopup/0.4.0/picpopup":"modules/picpopup/0.4.0/picpopup.js",
  "input/0.2.0/input":"modules/input/0.2.0/input.js",
  "button/0.4.0/button":"modules/button/0.4.0/button.js",
  "formrow/0.4.0/formrow":"modules/formrow/0.4.0/formrow.js",
  "combobox/0.4.0/combobox":"modules/combobox/0.4.0/combobox.js",
  "checkboxgroup/0.4.0/checkboxgroup":"modules/checkboxgroup/0.4.0/checkboxgroup.js",
  "combotree/0.4.0/combotree":"modules/combotree/0.4.0/combotree.js",
  "combo/0.4.0/combo":"modules/combo/0.4.0/combo.js",
  "tree/0.4.0/tree":"modules/tree/0.4.0/tree.js",
  "base/0.3.1/react-base": "modules/base/0.3.1/react-base.js",
  "base/0.4.0/react-base": "modules/base/0.4.0/react-base.js",
  "base/0.4.0/react-methods": "modules/base/0.4.0/react-methods.js",
  "input/0.4.0/input": "modules/input/0.4.0/input.js",
  "checkbox/0.4.0/checkbox": "modules/checkbox/0.4.0/checkbox.js",
  "base/0.3.1/react-module": "modules/base/0.3.1/react-module.js",
  "datepicker/0.3.1/datepicker": "modules/datepicker/0.3.1/datepicker.js",
  "uplodify/0.1.0/h5upload": "modules/uplodify/0.1.0/h5upload.js",
  "timer/0.1.0/index": "modules/timer/0.1.0/index",
  "timer/0.2.0/pc": "modules/timer/0.2.0/pc"
}
